export type ExercisePosterAsset = {
  slug: string;
  available: boolean;
  posterSrc: string | null;
  targetSrc?: string | null;
  stepSrcs: string[];
  stepCount: number;
};

export const EXERCISE_POSTER_ASSETS: Record<string, ExercisePosterAsset> = {
  "ab-crunch-machine": {
    slug: "ab-crunch-machine",
    available: true,
    posterSrc: "/exercise-posters/ab-crunch-machine/poster.webp",
    targetSrc: "/exercise-posters/ab-crunch-machine/target.webp",
    stepSrcs: ["/exercise-posters/ab-crunch-machine/step-1.webp", "/exercise-posters/ab-crunch-machine/step-2.webp", "/exercise-posters/ab-crunch-machine/step-3.webp", "/exercise-posters/ab-crunch-machine/step-4.webp", "/exercise-posters/ab-crunch-machine/step-5.webp"],
    stepCount: 5,
  },
  "ab-wheel-rollout": {
    slug: "ab-wheel-rollout",
    available: true,
    posterSrc: "/exercise-posters/ab-wheel-rollout/poster.webp",
    targetSrc: "/exercise-posters/ab-wheel-rollout/target.webp",
    stepSrcs: ["/exercise-posters/ab-wheel-rollout/step-1.webp", "/exercise-posters/ab-wheel-rollout/step-2.webp", "/exercise-posters/ab-wheel-rollout/step-3.webp", "/exercise-posters/ab-wheel-rollout/step-4.webp", "/exercise-posters/ab-wheel-rollout/step-5.webp"],
    stepCount: 5,
  },
  "alternating-dumbbell-curl": {
    slug: "alternating-dumbbell-curl",
    available: true,
    posterSrc: "/exercise-posters/alternating-dumbbell-curl/poster.webp",
    targetSrc: "/exercise-posters/alternating-dumbbell-curl/target.webp",
    stepSrcs: ["/exercise-posters/alternating-dumbbell-curl/step-1.webp", "/exercise-posters/alternating-dumbbell-curl/step-2.webp", "/exercise-posters/alternating-dumbbell-curl/step-3.webp", "/exercise-posters/alternating-dumbbell-curl/step-4.webp", "/exercise-posters/alternating-dumbbell-curl/step-5.webp"],
    stepCount: 5,
  },
  "assisted-dip-machine": {
    slug: "assisted-dip-machine",
    available: true,
    posterSrc: "/exercise-posters/assisted-dip-machine/poster.webp",
    targetSrc: "/exercise-posters/assisted-dip-machine/target.webp",
    stepSrcs: ["/exercise-posters/assisted-dip-machine/step-1.webp", "/exercise-posters/assisted-dip-machine/step-2.webp", "/exercise-posters/assisted-dip-machine/step-3.webp", "/exercise-posters/assisted-dip-machine/step-4.webp", "/exercise-posters/assisted-dip-machine/step-5.webp"],
    stepCount: 5,
  },
  "assisted-pull-up": {
    slug: "assisted-pull-up",
    available: true,
    posterSrc: "/exercise-posters/assisted-pull-up/poster.webp",
    targetSrc: "/exercise-posters/assisted-pull-up/target.webp",
    stepSrcs: ["/exercise-posters/assisted-pull-up/step-1.webp", "/exercise-posters/assisted-pull-up/step-2.webp", "/exercise-posters/assisted-pull-up/step-3.webp", "/exercise-posters/assisted-pull-up/step-4.webp", "/exercise-posters/assisted-pull-up/step-5.webp"],
    stepCount: 5,
  },
  "barbell-back-squat": {
    slug: "barbell-back-squat",
    available: true,
    posterSrc: "/exercise-posters/barbell-back-squat/poster.webp",
    targetSrc: "/exercise-posters/barbell-back-squat/target.webp",
    stepSrcs: ["/exercise-posters/barbell-back-squat/step-1.webp", "/exercise-posters/barbell-back-squat/step-2.webp", "/exercise-posters/barbell-back-squat/step-3.webp", "/exercise-posters/barbell-back-squat/step-4.webp", "/exercise-posters/barbell-back-squat/step-5.webp"],
    stepCount: 5,
  },
  "barbell-bench-press": {
    slug: "barbell-bench-press",
    available: true,
    posterSrc: "/exercise-posters/barbell-bench-press/poster.webp",
    targetSrc: "/exercise-posters/barbell-bench-press/target.webp",
    stepSrcs: ["/exercise-posters/barbell-bench-press/step-1.webp", "/exercise-posters/barbell-bench-press/step-2.webp", "/exercise-posters/barbell-bench-press/step-3.webp", "/exercise-posters/barbell-bench-press/step-4.webp", "/exercise-posters/barbell-bench-press/step-5.webp"],
    stepCount: 5,
  },
  "barbell-curl": {
    slug: "barbell-curl",
    available: true,
    posterSrc: "/exercise-posters/barbell-curl/poster.webp",
    targetSrc: "/exercise-posters/barbell-curl/target.webp",
    stepSrcs: ["/exercise-posters/barbell-curl/step-1.webp", "/exercise-posters/barbell-curl/step-2.webp", "/exercise-posters/barbell-curl/step-3.webp", "/exercise-posters/barbell-curl/step-4.webp", "/exercise-posters/barbell-curl/step-5.webp"],
    stepCount: 5,
  },
  "bulgarian-split-squat": {
    slug: "bulgarian-split-squat",
    available: true,
    posterSrc: "/exercise-posters/bulgarian-split-squat/poster.webp",
    targetSrc: "/exercise-posters/bulgarian-split-squat/target.webp",
    stepSrcs: ["/exercise-posters/bulgarian-split-squat/step-1.webp", "/exercise-posters/bulgarian-split-squat/step-2.webp", "/exercise-posters/bulgarian-split-squat/step-3.webp", "/exercise-posters/bulgarian-split-squat/step-4.webp", "/exercise-posters/bulgarian-split-squat/step-5.webp"],
    stepCount: 5,
  },
  "cable-crunch": {
    slug: "cable-crunch",
    available: true,
    posterSrc: "/exercise-posters/cable-crunch/poster.webp",
    targetSrc: "/exercise-posters/cable-crunch/target.webp",
    stepSrcs: ["/exercise-posters/cable-crunch/step-1.webp", "/exercise-posters/cable-crunch/step-2.webp", "/exercise-posters/cable-crunch/step-3.webp", "/exercise-posters/cable-crunch/step-4.webp", "/exercise-posters/cable-crunch/step-5.webp"],
    stepCount: 5,
  },
  "dumbbell-bench-press": {
    slug: "dumbbell-bench-press",
    available: true,
    posterSrc: "/exercise-posters/dumbbell-bench-press/poster.webp",
    targetSrc: "/exercise-posters/dumbbell-bench-press/target.webp",
    stepSrcs: ["/exercise-posters/dumbbell-bench-press/step-1.webp", "/exercise-posters/dumbbell-bench-press/step-2.webp", "/exercise-posters/dumbbell-bench-press/step-3.webp", "/exercise-posters/dumbbell-bench-press/step-4.webp", "/exercise-posters/dumbbell-bench-press/step-5.webp"],
    stepCount: 5,
  },
  "dumbbell-lateral-raise": {
    slug: "dumbbell-lateral-raise",
    available: true,
    posterSrc: "/exercise-posters/dumbbell-lateral-raise/poster.webp",
    targetSrc: "/exercise-posters/dumbbell-lateral-raise/target.webp",
    stepSrcs: ["/exercise-posters/dumbbell-lateral-raise/step-1.webp", "/exercise-posters/dumbbell-lateral-raise/step-2.webp", "/exercise-posters/dumbbell-lateral-raise/step-3.webp", "/exercise-posters/dumbbell-lateral-raise/step-4.webp", "/exercise-posters/dumbbell-lateral-raise/step-5.webp"],
    stepCount: 5,
  },
  "dumbbell-shoulder-press": {
    slug: "dumbbell-shoulder-press",
    available: true,
    posterSrc: "/exercise-posters/dumbbell-shoulder-press/poster.webp",
    targetSrc: "/exercise-posters/dumbbell-shoulder-press/target.webp",
    stepSrcs: ["/exercise-posters/dumbbell-shoulder-press/step-1.webp", "/exercise-posters/dumbbell-shoulder-press/step-2.webp", "/exercise-posters/dumbbell-shoulder-press/step-3.webp", "/exercise-posters/dumbbell-shoulder-press/step-4.webp", "/exercise-posters/dumbbell-shoulder-press/step-5.webp"],
    stepCount: 5,
  },
  "hack-squat-machine": {
    slug: "hack-squat-machine",
    available: true,
    posterSrc: "/exercise-posters/hack-squat-machine/poster.webp",
    targetSrc: "/exercise-posters/hack-squat-machine/target.webp",
    stepSrcs: ["/exercise-posters/hack-squat-machine/step-1.webp", "/exercise-posters/hack-squat-machine/step-2.webp", "/exercise-posters/hack-squat-machine/step-3.webp", "/exercise-posters/hack-squat-machine/step-4.webp", "/exercise-posters/hack-squat-machine/step-5.webp"],
    stepCount: 5,
  },
  "hammer-curl": {
    slug: "hammer-curl",
    available: true,
    posterSrc: "/exercise-posters/hammer-curl/poster.webp",
    targetSrc: "/exercise-posters/hammer-curl/target.webp",
    stepSrcs: ["/exercise-posters/hammer-curl/step-1.webp", "/exercise-posters/hammer-curl/step-2.webp", "/exercise-posters/hammer-curl/step-3.webp", "/exercise-posters/hammer-curl/step-4.webp", "/exercise-posters/hammer-curl/step-5.webp"],
    stepCount: 5,
  },
  "hip-thrust-machine": {
    slug: "hip-thrust-machine",
    available: true,
    posterSrc: "/exercise-posters/hip-thrust-machine/poster.webp",
    targetSrc: "/exercise-posters/hip-thrust-machine/target.webp",
    stepSrcs: ["/exercise-posters/hip-thrust-machine/step-1.webp", "/exercise-posters/hip-thrust-machine/step-2.webp", "/exercise-posters/hip-thrust-machine/step-3.webp", "/exercise-posters/hip-thrust-machine/step-4.webp", "/exercise-posters/hip-thrust-machine/step-5.webp"],
    stepCount: 5,
  },
  "incline-dumbbell-press": {
    slug: "incline-dumbbell-press",
    available: false,
    posterSrc: null,
    targetSrc: null,
    stepSrcs: [],
    stepCount: 0,
  },
  "lat-pulldown": {
    slug: "lat-pulldown",
    available: true,
    posterSrc: "/exercise-posters/lat-pulldown/poster.webp",
    targetSrc: "/exercise-posters/lat-pulldown/target.webp",
    stepSrcs: ["/exercise-posters/lat-pulldown/step-1.webp", "/exercise-posters/lat-pulldown/step-2.webp", "/exercise-posters/lat-pulldown/step-3.webp", "/exercise-posters/lat-pulldown/step-4.webp", "/exercise-posters/lat-pulldown/step-5.webp"],
    stepCount: 5,
  },
  "leg-extension-machine": {
    slug: "leg-extension-machine",
    available: true,
    posterSrc: "/exercise-posters/leg-extension-machine/poster.webp",
    targetSrc: "/exercise-posters/leg-extension-machine/target.webp",
    stepSrcs: ["/exercise-posters/leg-extension-machine/step-1.webp", "/exercise-posters/leg-extension-machine/step-2.webp", "/exercise-posters/leg-extension-machine/step-3.webp", "/exercise-posters/leg-extension-machine/step-4.webp", "/exercise-posters/leg-extension-machine/step-5.webp"],
    stepCount: 5,
  },
  "leg-press": {
    slug: "leg-press",
    available: true,
    posterSrc: "/exercise-posters/leg-press/poster.webp",
    targetSrc: "/exercise-posters/leg-press/target.webp",
    stepSrcs: ["/exercise-posters/leg-press/step-1.webp", "/exercise-posters/leg-press/step-2.webp", "/exercise-posters/leg-press/step-3.webp", "/exercise-posters/leg-press/step-4.webp", "/exercise-posters/leg-press/step-5.webp"],
    stepCount: 5,
  },
  "machine-chest-press": {
    slug: "machine-chest-press",
    available: true,
    posterSrc: "/exercise-posters/machine-chest-press/poster.webp",
    targetSrc: "/exercise-posters/machine-chest-press/target.webp",
    stepSrcs: ["/exercise-posters/machine-chest-press/step-1.webp", "/exercise-posters/machine-chest-press/step-2.webp", "/exercise-posters/machine-chest-press/step-3.webp", "/exercise-posters/machine-chest-press/step-4.webp", "/exercise-posters/machine-chest-press/step-5.webp"],
    stepCount: 5,
  },
  "pec-deck-fly": {
    slug: "pec-deck-fly",
    available: true,
    posterSrc: "/exercise-posters/pec-deck-fly/poster.webp",
    targetSrc: "/exercise-posters/pec-deck-fly/target.webp",
    stepSrcs: ["/exercise-posters/pec-deck-fly/step-1.webp", "/exercise-posters/pec-deck-fly/step-2.webp", "/exercise-posters/pec-deck-fly/step-3.webp", "/exercise-posters/pec-deck-fly/step-4.webp", "/exercise-posters/pec-deck-fly/step-5.webp"],
    stepCount: 5,
  },
  "plank": {
    slug: "plank",
    available: true,
    posterSrc: "/exercise-posters/plank/poster.webp",
    targetSrc: "/exercise-posters/plank/target.webp",
    stepSrcs: ["/exercise-posters/plank/step-1.webp", "/exercise-posters/plank/step-2.webp", "/exercise-posters/plank/step-3.webp", "/exercise-posters/plank/step-4.webp", "/exercise-posters/plank/step-5.webp"],
    stepCount: 5,
  },
  "preacher-curl-machine": {
    slug: "preacher-curl-machine",
    available: true,
    posterSrc: "/exercise-posters/preacher-curl-machine/poster.webp",
    targetSrc: "/exercise-posters/preacher-curl-machine/target.webp",
    stepSrcs: ["/exercise-posters/preacher-curl-machine/step-1.webp", "/exercise-posters/preacher-curl-machine/step-2.webp", "/exercise-posters/preacher-curl-machine/step-3.webp", "/exercise-posters/preacher-curl-machine/step-4.webp", "/exercise-posters/preacher-curl-machine/step-5.webp"],
    stepCount: 5,
  },
  "romanian-deadlift": {
    slug: "romanian-deadlift",
    available: true,
    posterSrc: "/exercise-posters/romanian-deadlift/poster.webp",
    targetSrc: "/exercise-posters/romanian-deadlift/target.webp",
    stepSrcs: ["/exercise-posters/romanian-deadlift/step-1.webp", "/exercise-posters/romanian-deadlift/step-2.webp", "/exercise-posters/romanian-deadlift/step-3.webp", "/exercise-posters/romanian-deadlift/step-4.webp", "/exercise-posters/romanian-deadlift/step-5.webp"],
    stepCount: 5,
  },
  "rope-triceps-pushdown": {
    slug: "rope-triceps-pushdown",
    available: true,
    posterSrc: "/exercise-posters/rope-triceps-pushdown/poster.webp",
    targetSrc: "/exercise-posters/rope-triceps-pushdown/target.webp",
    stepSrcs: ["/exercise-posters/rope-triceps-pushdown/step-1.webp", "/exercise-posters/rope-triceps-pushdown/step-2.webp", "/exercise-posters/rope-triceps-pushdown/step-3.webp", "/exercise-posters/rope-triceps-pushdown/step-4.webp", "/exercise-posters/rope-triceps-pushdown/step-5.webp"],
    stepCount: 5,
  },
  "seated-cable-row": {
    slug: "seated-cable-row",
    available: true,
    posterSrc: "/exercise-posters/seated-cable-row/poster.webp",
    targetSrc: "/exercise-posters/seated-cable-row/target.webp",
    stepSrcs: ["/exercise-posters/seated-cable-row/step-1.webp", "/exercise-posters/seated-cable-row/step-2.webp", "/exercise-posters/seated-cable-row/step-3.webp", "/exercise-posters/seated-cable-row/step-4.webp", "/exercise-posters/seated-cable-row/step-5.webp"],
    stepCount: 5,
  },
  "seated-leg-curl-machine": {
    slug: "seated-leg-curl-machine",
    available: false,
    posterSrc: null,
    targetSrc: null,
    stepSrcs: [],
    stepCount: 0,
  },
  "standing-calf-raise-machine": {
    slug: "standing-calf-raise-machine",
    available: true,
    posterSrc: "/exercise-posters/standing-calf-raise-machine/poster.webp",
    targetSrc: "/exercise-posters/standing-calf-raise-machine/target.webp",
    stepSrcs: ["/exercise-posters/standing-calf-raise-machine/step-1.webp", "/exercise-posters/standing-calf-raise-machine/step-2.webp", "/exercise-posters/standing-calf-raise-machine/step-3.webp", "/exercise-posters/standing-calf-raise-machine/step-4.webp", "/exercise-posters/standing-calf-raise-machine/step-5.webp"],
    stepCount: 5,
  },
  "treadmill-walk": {
    slug: "treadmill-walk",
    available: true,
    posterSrc: "/exercise-posters/treadmill-walk/poster.webp",
    targetSrc: "/exercise-posters/treadmill-walk/target.webp",
    stepSrcs: ["/exercise-posters/treadmill-walk/step-1.webp", "/exercise-posters/treadmill-walk/step-2.webp", "/exercise-posters/treadmill-walk/step-3.webp", "/exercise-posters/treadmill-walk/step-4.webp", "/exercise-posters/treadmill-walk/step-5.webp"],
    stepCount: 5,
  },
};

export function getExercisePosterAsset(slug?: string | null): ExercisePosterAsset | null {
  if (!slug) return null;
  return EXERCISE_POSTER_ASSETS[slug] ?? null;
}