export type ExerciseSplitAsset = {
  slug: string;
  available: boolean;
  exerciseName: string;
  stepSrcs: string[];
  musclesSrc: string | null;
  tipsSrc: string | null;
  mistakesSrc: string | null;
  stepCount: number;
};

export const EXERCISE_SPLIT_ASSETS: Record<string, ExerciseSplitAsset> = {
  "ab-crunch-machine": {
    slug: "ab-crunch-machine",
    available: true,
    exerciseName: "Ab Crunch Machine",
    stepSrcs: ["/exercise-guides-hd/ab-crunch-machine/step-1.webp", "/exercise-guides-hd/ab-crunch-machine/step-2.webp", "/exercise-guides-hd/ab-crunch-machine/step-3.webp", "/exercise-guides-hd/ab-crunch-machine/step-4.webp", "/exercise-guides-hd/ab-crunch-machine/step-5.webp"],
    musclesSrc: "/exercise-guides-hd/ab-crunch-machine/muscles.webp",
    tipsSrc: "/exercise-guides-hd/ab-crunch-machine/tips.webp",
    mistakesSrc: "/exercise-guides-hd/ab-crunch-machine/mistakes.webp",
    stepCount: 5,
  },
  "ab-wheel-rollout": {
    slug: "ab-wheel-rollout",
    available: true,
    exerciseName: "Ab Wheel Rollout",
    stepSrcs: ["/exercise-guides-hd/ab-wheel-rollout/step-1.webp", "/exercise-guides-hd/ab-wheel-rollout/step-2.webp", "/exercise-guides-hd/ab-wheel-rollout/step-3.webp", "/exercise-guides-hd/ab-wheel-rollout/step-4.webp", "/exercise-guides-hd/ab-wheel-rollout/step-5.webp", "/exercise-guides-hd/ab-wheel-rollout/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/ab-wheel-rollout/muscles.webp",
    tipsSrc: "/exercise-guides-hd/ab-wheel-rollout/tips.webp",
    mistakesSrc: "/exercise-guides-hd/ab-wheel-rollout/mistakes.webp",
    stepCount: 6,
  },
  "alternating-dumbbell-curl": {
    slug: "alternating-dumbbell-curl",
    available: true,
    exerciseName: "Alternating Dumbbell Curl",
    stepSrcs: ["/exercise-guides-hd/alternating-dumbbell-curl/step-1.webp", "/exercise-guides-hd/alternating-dumbbell-curl/step-2.webp", "/exercise-guides-hd/alternating-dumbbell-curl/step-3.webp", "/exercise-guides-hd/alternating-dumbbell-curl/step-4.webp", "/exercise-guides-hd/alternating-dumbbell-curl/step-5.webp"],
    musclesSrc: "/exercise-guides-hd/alternating-dumbbell-curl/muscles.webp",
    tipsSrc: "/exercise-guides-hd/alternating-dumbbell-curl/tips.webp",
    mistakesSrc: "/exercise-guides-hd/alternating-dumbbell-curl/mistakes.webp",
    stepCount: 5,
  },
  "assisted-dip-machine": {
    slug: "assisted-dip-machine",
    available: true,
    exerciseName: "Assisted Dip Machine",
    stepSrcs: ["/exercise-guides-hd/assisted-dip-machine/step-1.webp", "/exercise-guides-hd/assisted-dip-machine/step-2.webp", "/exercise-guides-hd/assisted-dip-machine/step-3.webp", "/exercise-guides-hd/assisted-dip-machine/step-4.webp", "/exercise-guides-hd/assisted-dip-machine/step-5.webp", "/exercise-guides-hd/assisted-dip-machine/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/assisted-dip-machine/muscles.webp",
    tipsSrc: "/exercise-guides-hd/assisted-dip-machine/tips.webp",
    mistakesSrc: "/exercise-guides-hd/assisted-dip-machine/mistakes.webp",
    stepCount: 6,
  },
  "assisted-pull-up": {
    slug: "assisted-pull-up",
    available: true,
    exerciseName: "Assisted Pull-Up",
    stepSrcs: ["/exercise-guides-hd/assisted-pull-up/step-1.webp", "/exercise-guides-hd/assisted-pull-up/step-2.webp", "/exercise-guides-hd/assisted-pull-up/step-3.webp", "/exercise-guides-hd/assisted-pull-up/step-4.webp", "/exercise-guides-hd/assisted-pull-up/step-5.webp", "/exercise-guides-hd/assisted-pull-up/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/assisted-pull-up/muscles.webp",
    tipsSrc: "/exercise-guides-hd/assisted-pull-up/tips.webp",
    mistakesSrc: "/exercise-guides-hd/assisted-pull-up/mistakes.webp",
    stepCount: 6,
  },
  "barbell-back-squat": {
    slug: "barbell-back-squat",
    available: true,
    exerciseName: "Barbell Back Squat",
    stepSrcs: ["/exercise-guides-hd/barbell-back-squat/step-1.webp", "/exercise-guides-hd/barbell-back-squat/step-2.webp", "/exercise-guides-hd/barbell-back-squat/step-3.webp", "/exercise-guides-hd/barbell-back-squat/step-4.webp", "/exercise-guides-hd/barbell-back-squat/step-5.webp", "/exercise-guides-hd/barbell-back-squat/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/barbell-back-squat/muscles.webp",
    tipsSrc: "/exercise-guides-hd/barbell-back-squat/tips.webp",
    mistakesSrc: "/exercise-guides-hd/barbell-back-squat/mistakes.webp",
    stepCount: 6,
  },
  "barbell-bench-press": {
    slug: "barbell-bench-press",
    available: true,
    exerciseName: "Barbell Bench Press",
    stepSrcs: ["/exercise-guides-hd/barbell-bench-press/step-1.webp", "/exercise-guides-hd/barbell-bench-press/step-2.webp", "/exercise-guides-hd/barbell-bench-press/step-3.webp", "/exercise-guides-hd/barbell-bench-press/step-4.webp", "/exercise-guides-hd/barbell-bench-press/step-5.webp", "/exercise-guides-hd/barbell-bench-press/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/barbell-bench-press/muscles.webp",
    tipsSrc: "/exercise-guides-hd/barbell-bench-press/tips.webp",
    mistakesSrc: "/exercise-guides-hd/barbell-bench-press/mistakes.webp",
    stepCount: 6,
  },
  "barbell-curl": {
    slug: "barbell-curl",
    available: true,
    exerciseName: "Barbell Curl",
    stepSrcs: ["/exercise-guides-hd/barbell-curl/step-1.webp", "/exercise-guides-hd/barbell-curl/step-2.webp", "/exercise-guides-hd/barbell-curl/step-3.webp", "/exercise-guides-hd/barbell-curl/step-4.webp", "/exercise-guides-hd/barbell-curl/step-5.webp", "/exercise-guides-hd/barbell-curl/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/barbell-curl/muscles.webp",
    tipsSrc: "/exercise-guides-hd/barbell-curl/tips.webp",
    mistakesSrc: "/exercise-guides-hd/barbell-curl/mistakes.webp",
    stepCount: 6,
  },
  "bulgarian-split-squat": {
    slug: "bulgarian-split-squat",
    available: true,
    exerciseName: "Bulgarian Split Squat",
    stepSrcs: ["/exercise-guides-hd/bulgarian-split-squat/step-1.webp", "/exercise-guides-hd/bulgarian-split-squat/step-2.webp", "/exercise-guides-hd/bulgarian-split-squat/step-3.webp", "/exercise-guides-hd/bulgarian-split-squat/step-4.webp", "/exercise-guides-hd/bulgarian-split-squat/step-5.webp", "/exercise-guides-hd/bulgarian-split-squat/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/bulgarian-split-squat/muscles.webp",
    tipsSrc: "/exercise-guides-hd/bulgarian-split-squat/tips.webp",
    mistakesSrc: "/exercise-guides-hd/bulgarian-split-squat/mistakes.webp",
    stepCount: 6,
  },
  "cable-crunch": {
    slug: "cable-crunch",
    available: true,
    exerciseName: "Cable Crunch",
    stepSrcs: ["/exercise-guides-hd/cable-crunch/step-1.webp", "/exercise-guides-hd/cable-crunch/step-2.webp", "/exercise-guides-hd/cable-crunch/step-3.webp", "/exercise-guides-hd/cable-crunch/step-4.webp", "/exercise-guides-hd/cable-crunch/step-5.webp", "/exercise-guides-hd/cable-crunch/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/cable-crunch/muscles.webp",
    tipsSrc: "/exercise-guides-hd/cable-crunch/tips.webp",
    mistakesSrc: "/exercise-guides-hd/cable-crunch/mistakes.webp",
    stepCount: 6,
  },
  "dumbbell-bench-press": {
    slug: "dumbbell-bench-press",
    available: true,
    exerciseName: "dumbell bench press",
    stepSrcs: ["/exercise-guides-hd/dumbbell-bench-press/step-1.webp", "/exercise-guides-hd/dumbbell-bench-press/step-2.webp", "/exercise-guides-hd/dumbbell-bench-press/step-3.webp", "/exercise-guides-hd/dumbbell-bench-press/step-4.webp", "/exercise-guides-hd/dumbbell-bench-press/step-5.webp", "/exercise-guides-hd/dumbbell-bench-press/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/dumbbell-bench-press/muscles.webp",
    tipsSrc: "/exercise-guides-hd/dumbbell-bench-press/tips.webp",
    mistakesSrc: "/exercise-guides-hd/dumbbell-bench-press/mistakes.webp",
    stepCount: 6,
  },
  "dumbbell-lateral-raise": {
    slug: "dumbbell-lateral-raise",
    available: true,
    exerciseName: "Dumbbell Lateral Raise",
    stepSrcs: ["/exercise-guides-hd/dumbbell-lateral-raise/step-1.webp", "/exercise-guides-hd/dumbbell-lateral-raise/step-2.webp", "/exercise-guides-hd/dumbbell-lateral-raise/step-3.webp", "/exercise-guides-hd/dumbbell-lateral-raise/step-4.webp", "/exercise-guides-hd/dumbbell-lateral-raise/step-5.webp", "/exercise-guides-hd/dumbbell-lateral-raise/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/dumbbell-lateral-raise/muscles.webp",
    tipsSrc: "/exercise-guides-hd/dumbbell-lateral-raise/tips.webp",
    mistakesSrc: "/exercise-guides-hd/dumbbell-lateral-raise/mistakes.webp",
    stepCount: 6,
  },
  "dumbbell-shoulder-press": {
    slug: "dumbbell-shoulder-press",
    available: true,
    exerciseName: "Dumbbell Shoulder Press",
    stepSrcs: ["/exercise-guides-hd/dumbbell-shoulder-press/step-1.webp", "/exercise-guides-hd/dumbbell-shoulder-press/step-2.webp", "/exercise-guides-hd/dumbbell-shoulder-press/step-3.webp", "/exercise-guides-hd/dumbbell-shoulder-press/step-4.webp", "/exercise-guides-hd/dumbbell-shoulder-press/step-5.webp", "/exercise-guides-hd/dumbbell-shoulder-press/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/dumbbell-shoulder-press/muscles.webp",
    tipsSrc: "/exercise-guides-hd/dumbbell-shoulder-press/tips.webp",
    mistakesSrc: "/exercise-guides-hd/dumbbell-shoulder-press/mistakes.webp",
    stepCount: 6,
  },
  "hack-squat-machine": {
    slug: "hack-squat-machine",
    available: true,
    exerciseName: "Hack Squat Machine",
    stepSrcs: ["/exercise-guides-hd/hack-squat-machine/step-1.webp", "/exercise-guides-hd/hack-squat-machine/step-2.webp", "/exercise-guides-hd/hack-squat-machine/step-3.webp", "/exercise-guides-hd/hack-squat-machine/step-4.webp", "/exercise-guides-hd/hack-squat-machine/step-5.webp", "/exercise-guides-hd/hack-squat-machine/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/hack-squat-machine/muscles.webp",
    tipsSrc: "/exercise-guides-hd/hack-squat-machine/tips.webp",
    mistakesSrc: "/exercise-guides-hd/hack-squat-machine/mistakes.webp",
    stepCount: 6,
  },
  "hammer-curl": {
    slug: "hammer-curl",
    available: true,
    exerciseName: "Hammer Curl",
    stepSrcs: ["/exercise-guides-hd/hammer-curl/step-1.webp", "/exercise-guides-hd/hammer-curl/step-2.webp", "/exercise-guides-hd/hammer-curl/step-3.webp", "/exercise-guides-hd/hammer-curl/step-4.webp", "/exercise-guides-hd/hammer-curl/step-5.webp", "/exercise-guides-hd/hammer-curl/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/hammer-curl/muscles.webp",
    tipsSrc: "/exercise-guides-hd/hammer-curl/tips.webp",
    mistakesSrc: "/exercise-guides-hd/hammer-curl/mistakes.webp",
    stepCount: 6,
  },
  "hip-thrust-machine": {
    slug: "hip-thrust-machine",
    available: true,
    exerciseName: "Hip Thrust Machine",
    stepSrcs: ["/exercise-guides-hd/hip-thrust-machine/step-1.webp", "/exercise-guides-hd/hip-thrust-machine/step-2.webp", "/exercise-guides-hd/hip-thrust-machine/step-3.webp", "/exercise-guides-hd/hip-thrust-machine/step-4.webp", "/exercise-guides-hd/hip-thrust-machine/step-5.webp", "/exercise-guides-hd/hip-thrust-machine/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/hip-thrust-machine/muscles.webp",
    tipsSrc: "/exercise-guides-hd/hip-thrust-machine/tips.webp",
    mistakesSrc: "/exercise-guides-hd/hip-thrust-machine/mistakes.webp",
    stepCount: 6,
  },
  "incline-dumbbell-press": {
    slug: "incline-dumbbell-press",
    available: false,
    exerciseName: "Incline Dumbbell Press",
    stepSrcs: [],
    musclesSrc: null,
    tipsSrc: null,
    mistakesSrc: null,
    stepCount: 0,
  },
  "lat-pulldown": {
    slug: "lat-pulldown",
    available: true,
    exerciseName: "Lat Pulldown",
    stepSrcs: ["/exercise-guides-hd/lat-pulldown/step-1.webp", "/exercise-guides-hd/lat-pulldown/step-2.webp", "/exercise-guides-hd/lat-pulldown/step-3.webp", "/exercise-guides-hd/lat-pulldown/step-4.webp", "/exercise-guides-hd/lat-pulldown/step-5.webp", "/exercise-guides-hd/lat-pulldown/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/lat-pulldown/muscles.webp",
    tipsSrc: "/exercise-guides-hd/lat-pulldown/tips.webp",
    mistakesSrc: "/exercise-guides-hd/lat-pulldown/mistakes.webp",
    stepCount: 6,
  },
  "leg-extension-machine": {
    slug: "leg-extension-machine",
    available: true,
    exerciseName: "Leg Extension Machine",
    stepSrcs: ["/exercise-guides-hd/leg-extension-machine/step-1.webp", "/exercise-guides-hd/leg-extension-machine/step-2.webp", "/exercise-guides-hd/leg-extension-machine/step-3.webp", "/exercise-guides-hd/leg-extension-machine/step-4.webp", "/exercise-guides-hd/leg-extension-machine/step-5.webp", "/exercise-guides-hd/leg-extension-machine/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/leg-extension-machine/muscles.webp",
    tipsSrc: "/exercise-guides-hd/leg-extension-machine/tips.webp",
    mistakesSrc: "/exercise-guides-hd/leg-extension-machine/mistakes.webp",
    stepCount: 6,
  },
  "leg-press": {
    slug: "leg-press",
    available: true,
    exerciseName: "Leg Press",
    stepSrcs: ["/exercise-guides-hd/leg-press/step-1.webp", "/exercise-guides-hd/leg-press/step-2.webp", "/exercise-guides-hd/leg-press/step-3.webp", "/exercise-guides-hd/leg-press/step-4.webp", "/exercise-guides-hd/leg-press/step-5.webp", "/exercise-guides-hd/leg-press/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/leg-press/muscles.webp",
    tipsSrc: "/exercise-guides-hd/leg-press/tips.webp",
    mistakesSrc: "/exercise-guides-hd/leg-press/mistakes.webp",
    stepCount: 6,
  },
  "machine-chest-press": {
    slug: "machine-chest-press",
    available: true,
    exerciseName: "Machine Chest Press",
    stepSrcs: ["/exercise-guides-hd/machine-chest-press/step-1.webp", "/exercise-guides-hd/machine-chest-press/step-2.webp", "/exercise-guides-hd/machine-chest-press/step-3.webp", "/exercise-guides-hd/machine-chest-press/step-4.webp", "/exercise-guides-hd/machine-chest-press/step-5.webp", "/exercise-guides-hd/machine-chest-press/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/machine-chest-press/muscles.webp",
    tipsSrc: "/exercise-guides-hd/machine-chest-press/tips.webp",
    mistakesSrc: "/exercise-guides-hd/machine-chest-press/mistakes.webp",
    stepCount: 6,
  },
  "pec-deck-fly": {
    slug: "pec-deck-fly",
    available: true,
    exerciseName: "Pec Deck Fly",
    stepSrcs: ["/exercise-guides-hd/pec-deck-fly/step-1.webp", "/exercise-guides-hd/pec-deck-fly/step-2.webp", "/exercise-guides-hd/pec-deck-fly/step-3.webp", "/exercise-guides-hd/pec-deck-fly/step-4.webp", "/exercise-guides-hd/pec-deck-fly/step-5.webp", "/exercise-guides-hd/pec-deck-fly/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/pec-deck-fly/muscles.webp",
    tipsSrc: "/exercise-guides-hd/pec-deck-fly/tips.webp",
    mistakesSrc: "/exercise-guides-hd/pec-deck-fly/mistakes.webp",
    stepCount: 6,
  },
  "plank": {
    slug: "plank",
    available: true,
    exerciseName: "Plank",
    stepSrcs: ["/exercise-guides-hd/plank/step-1.webp", "/exercise-guides-hd/plank/step-2.webp", "/exercise-guides-hd/plank/step-3.webp", "/exercise-guides-hd/plank/step-4.webp", "/exercise-guides-hd/plank/step-5.webp"],
    musclesSrc: "/exercise-guides-hd/plank/muscles.webp",
    tipsSrc: "/exercise-guides-hd/plank/tips.webp",
    mistakesSrc: "/exercise-guides-hd/plank/mistakes.webp",
    stepCount: 5,
  },
  "preacher-curl-machine": {
    slug: "preacher-curl-machine",
    available: true,
    exerciseName: "Preacher Curl Machine",
    stepSrcs: ["/exercise-guides-hd/preacher-curl-machine/step-1.webp", "/exercise-guides-hd/preacher-curl-machine/step-2.webp", "/exercise-guides-hd/preacher-curl-machine/step-3.webp", "/exercise-guides-hd/preacher-curl-machine/step-4.webp", "/exercise-guides-hd/preacher-curl-machine/step-5.webp", "/exercise-guides-hd/preacher-curl-machine/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/preacher-curl-machine/muscles.webp",
    tipsSrc: "/exercise-guides-hd/preacher-curl-machine/tips.webp",
    mistakesSrc: "/exercise-guides-hd/preacher-curl-machine/mistakes.webp",
    stepCount: 6,
  },
  "romanian-deadlift": {
    slug: "romanian-deadlift",
    available: true,
    exerciseName: "Romanian Deadlift",
    stepSrcs: ["/exercise-guides-hd/romanian-deadlift/step-1.webp", "/exercise-guides-hd/romanian-deadlift/step-2.webp", "/exercise-guides-hd/romanian-deadlift/step-3.webp", "/exercise-guides-hd/romanian-deadlift/step-4.webp", "/exercise-guides-hd/romanian-deadlift/step-5.webp", "/exercise-guides-hd/romanian-deadlift/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/romanian-deadlift/muscles.webp",
    tipsSrc: "/exercise-guides-hd/romanian-deadlift/tips.webp",
    mistakesSrc: "/exercise-guides-hd/romanian-deadlift/mistakes.webp",
    stepCount: 6,
  },
  "rope-triceps-pushdown": {
    slug: "rope-triceps-pushdown",
    available: true,
    exerciseName: "Rope Triceps Pushdown",
    stepSrcs: ["/exercise-guides-hd/rope-triceps-pushdown/step-1.webp", "/exercise-guides-hd/rope-triceps-pushdown/step-2.webp", "/exercise-guides-hd/rope-triceps-pushdown/step-3.webp", "/exercise-guides-hd/rope-triceps-pushdown/step-4.webp", "/exercise-guides-hd/rope-triceps-pushdown/step-5.webp", "/exercise-guides-hd/rope-triceps-pushdown/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/rope-triceps-pushdown/muscles.webp",
    tipsSrc: "/exercise-guides-hd/rope-triceps-pushdown/tips.webp",
    mistakesSrc: "/exercise-guides-hd/rope-triceps-pushdown/mistakes.webp",
    stepCount: 6,
  },
  "seated-cable-row": {
    slug: "seated-cable-row",
    available: true,
    exerciseName: "Seated Cable Row",
    stepSrcs: ["/exercise-guides-hd/seated-cable-row/step-1.webp", "/exercise-guides-hd/seated-cable-row/step-2.webp", "/exercise-guides-hd/seated-cable-row/step-3.webp", "/exercise-guides-hd/seated-cable-row/step-4.webp", "/exercise-guides-hd/seated-cable-row/step-5.webp", "/exercise-guides-hd/seated-cable-row/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/seated-cable-row/muscles.webp",
    tipsSrc: "/exercise-guides-hd/seated-cable-row/tips.webp",
    mistakesSrc: "/exercise-guides-hd/seated-cable-row/mistakes.webp",
    stepCount: 6,
  },
  "seated-leg-curl-machine": {
    slug: "seated-leg-curl-machine",
    available: false,
    exerciseName: "Seated Leg Curl Machine",
    stepSrcs: [],
    musclesSrc: null,
    tipsSrc: null,
    mistakesSrc: null,
    stepCount: 0,
  },
  "standing-calf-raise-machine": {
    slug: "standing-calf-raise-machine",
    available: true,
    exerciseName: "Standing Calf Raise Machine",
    stepSrcs: ["/exercise-guides-hd/standing-calf-raise-machine/step-1.webp", "/exercise-guides-hd/standing-calf-raise-machine/step-2.webp", "/exercise-guides-hd/standing-calf-raise-machine/step-3.webp", "/exercise-guides-hd/standing-calf-raise-machine/step-4.webp", "/exercise-guides-hd/standing-calf-raise-machine/step-5.webp", "/exercise-guides-hd/standing-calf-raise-machine/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/standing-calf-raise-machine/muscles.webp",
    tipsSrc: "/exercise-guides-hd/standing-calf-raise-machine/tips.webp",
    mistakesSrc: "/exercise-guides-hd/standing-calf-raise-machine/mistakes.webp",
    stepCount: 6,
  },
  "treadmill-walk": {
    slug: "treadmill-walk",
    available: true,
    exerciseName: "Treadmill walk",
    stepSrcs: ["/exercise-guides-hd/treadmill-walk/step-1.webp", "/exercise-guides-hd/treadmill-walk/step-2.webp", "/exercise-guides-hd/treadmill-walk/step-3.webp", "/exercise-guides-hd/treadmill-walk/step-4.webp", "/exercise-guides-hd/treadmill-walk/step-5.webp", "/exercise-guides-hd/treadmill-walk/step-6.webp"],
    musclesSrc: "/exercise-guides-hd/treadmill-walk/muscles.webp",
    tipsSrc: "/exercise-guides-hd/treadmill-walk/tips.webp",
    mistakesSrc: "/exercise-guides-hd/treadmill-walk/mistakes.webp",
    stepCount: 6,
  },
};

export function getExerciseSplitAsset(slug?: string | null): ExerciseSplitAsset | null {
  if (!slug) return null;
  return EXERCISE_SPLIT_ASSETS[slug] ?? null;
}