begin;

create table if not exists public.app_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  source text not null,
  event_type text not null,
  severity text not null default 'info'
    check (severity in ('info', 'warning', 'error')),
  route text,
  message text,
  metadata jsonb not null default '{}'::jsonb,
  duration_ms numeric(12, 2),
  ai_model text,
  input_tokens bigint,
  output_tokens bigint,
  estimated_cost_usd numeric(14, 8),
  created_at timestamptz not null default now()
);

create index if not exists app_events_created_idx
  on public.app_events (created_at desc);

create index if not exists app_events_severity_created_idx
  on public.app_events (severity, created_at desc);

create index if not exists app_events_type_created_idx
  on public.app_events (event_type, created_at desc);

create index if not exists app_events_user_created_idx
  on public.app_events (user_id, created_at desc);

alter table public.app_events enable row level security;

-- Events are written and read only through authenticated server routes
-- using the service-role key. No browser-facing RLS policy is created.
revoke all on public.app_events from anon, authenticated;

comment on table public.app_events is
  'Privacy-minimized FitMate operational events, errors, latency, token usage, and configurable AI cost estimates.';

commit;
