begin;

create extension if not exists pgcrypto;

create table if not exists public.fitness_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  goal text not null,
  experience text not null,
  training_days text not null,
  difficulty text not null default 'medium'
    check (difficulty in ('easy', 'medium', 'hard')),
  age smallint not null check (age between 13 and 100),
  gender text not null,
  height numeric(5, 2) not null check (height between 100 and 250),
  weight numeric(6, 2) not null check (weight between 30 and 300),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workout_plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text,
  goal text not null,
  level text not null check (level in ('easy', 'medium', 'hard')),
  days_per_week smallint not null check (days_per_week between 1 and 7),
  status text not null default 'active'
    check (status in ('active', 'archived')),
  plan jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  category text not null,
  target_muscle text not null,
  secondary_muscles text[] not null default '{}',
  equipment text not null,
  difficulty text not null default 'medium'
    check (difficulty in ('easy', 'medium', 'hard')),
  movement_pattern text,
  description text,
  instructions text[] not null default '{}',
  tips text[] not null default '{}',
  animation_url text,
  video_url text,
  thumbnail_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workout_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  workout_plan_id bigint references public.workout_plans(id) on delete set null,
  workout_day smallint not null check (workout_day between 1 and 7),
  workout_name text not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null default 'in_progress'
    check (status in ('in_progress', 'completed', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (status = 'completed' and completed_at is not null)
    or status <> 'completed'
  )
);

create table if not exists public.workout_exercise_logs (
  id uuid primary key default gen_random_uuid(),
  workout_session_id uuid not null
    references public.workout_sessions(id) on delete cascade,
  exercise_id bigint references public.exercises(id) on delete set null,
  exercise_name text not null,
  workout_day smallint not null check (workout_day between 1 and 7),
  sets smallint not null check (sets between 1 and 20),
  reps text,
  completed boolean not null default false,
  completed_at timestamptz,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.weight_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  weight numeric(6, 2) not null check (weight between 1 and 499),
  recorded_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- Keep the migration usable for projects that already created an earlier,
-- incomplete version of these tables.
alter table public.fitness_profiles
  add column if not exists user_id uuid,
  add column if not exists goal text,
  add column if not exists experience text,
  add column if not exists training_days text,
  add column if not exists difficulty text default 'medium',
  add column if not exists age smallint,
  add column if not exists gender text,
  add column if not exists height numeric(5, 2),
  add column if not exists weight numeric(6, 2),
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.workout_plans
  add column if not exists user_id uuid,
  add column if not exists name text,
  add column if not exists description text,
  add column if not exists goal text,
  add column if not exists level text,
  add column if not exists days_per_week smallint,
  add column if not exists status text default 'active',
  add column if not exists plan jsonb,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.exercises
  add column if not exists name text,
  add column if not exists slug text,
  add column if not exists category text,
  add column if not exists target_muscle text,
  add column if not exists secondary_muscles text[] default '{}',
  add column if not exists equipment text,
  add column if not exists difficulty text default 'medium',
  add column if not exists movement_pattern text,
  add column if not exists description text,
  add column if not exists instructions text[] default '{}',
  add column if not exists tips text[] default '{}',
  add column if not exists animation_url text,
  add column if not exists video_url text,
  add column if not exists thumbnail_url text,
  add column if not exists is_active boolean default true,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.workout_sessions
  add column if not exists user_id uuid,
  add column if not exists workout_plan_id bigint,
  add column if not exists workout_day smallint,
  add column if not exists workout_name text,
  add column if not exists started_at timestamptz default now(),
  add column if not exists completed_at timestamptz,
  add column if not exists status text default 'in_progress',
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.workout_exercise_logs
  add column if not exists workout_session_id uuid,
  add column if not exists exercise_id bigint,
  add column if not exists exercise_name text,
  add column if not exists workout_day smallint,
  add column if not exists sets smallint,
  add column if not exists reps text,
  add column if not exists completed boolean default false,
  add column if not exists completed_at timestamptz,
  add column if not exists user_id uuid,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.weight_logs
  add column if not exists user_id uuid,
  add column if not exists weight numeric(6, 2),
  add column if not exists recorded_at timestamptz default now(),
  add column if not exists created_at timestamptz default now();

create unique index if not exists fitness_profiles_user_id_uidx
  on public.fitness_profiles (user_id);

create unique index if not exists workout_plans_user_id_uidx
  on public.workout_plans (user_id);

create unique index if not exists exercises_name_uidx
  on public.exercises (name);

create unique index if not exists exercises_slug_uidx
  on public.exercises (slug);

create index if not exists workout_sessions_user_started_idx
  on public.workout_sessions (user_id, started_at desc);

create index if not exists workout_sessions_plan_id_idx
  on public.workout_sessions (workout_plan_id);

create index if not exists workout_sessions_user_status_idx
  on public.workout_sessions (user_id, status);

create index if not exists workout_exercise_logs_session_idx
  on public.workout_exercise_logs (workout_session_id);

create index if not exists workout_exercise_logs_exercise_idx
  on public.workout_exercise_logs (exercise_id);

create index if not exists workout_exercise_logs_user_created_idx
  on public.workout_exercise_logs (user_id, created_at desc);

create index if not exists weight_logs_user_recorded_idx
  on public.weight_logs (user_id, recorded_at desc);

create index if not exists exercises_active_name_idx
  on public.exercises (is_active, name);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists fitness_profiles_set_updated_at
  on public.fitness_profiles;
create trigger fitness_profiles_set_updated_at
before update on public.fitness_profiles
for each row execute function public.set_updated_at();

drop trigger if exists workout_plans_set_updated_at
  on public.workout_plans;
create trigger workout_plans_set_updated_at
before update on public.workout_plans
for each row execute function public.set_updated_at();

drop trigger if exists exercises_set_updated_at
  on public.exercises;
create trigger exercises_set_updated_at
before update on public.exercises
for each row execute function public.set_updated_at();

drop trigger if exists workout_sessions_set_updated_at
  on public.workout_sessions;
create trigger workout_sessions_set_updated_at
before update on public.workout_sessions
for each row execute function public.set_updated_at();

drop trigger if exists workout_exercise_logs_set_updated_at
  on public.workout_exercise_logs;
create trigger workout_exercise_logs_set_updated_at
before update on public.workout_exercise_logs
for each row execute function public.set_updated_at();

alter table public.fitness_profiles enable row level security;
alter table public.workout_plans enable row level security;
alter table public.exercises enable row level security;
alter table public.workout_sessions enable row level security;
alter table public.workout_exercise_logs enable row level security;
alter table public.weight_logs enable row level security;

drop policy if exists fitness_profiles_owner_all
  on public.fitness_profiles;
create policy fitness_profiles_owner_all
on public.fitness_profiles
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists workout_plans_owner_all
  on public.workout_plans;
create policy workout_plans_owner_all
on public.workout_plans
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists exercises_public_read_active
  on public.exercises;
create policy exercises_public_read_active
on public.exercises
for select
to anon, authenticated
using (is_active);

drop policy if exists workout_sessions_owner_all
  on public.workout_sessions;
create policy workout_sessions_owner_all
on public.workout_sessions
for all
to authenticated
using ((select auth.uid()) = user_id)
with check (
  (select auth.uid()) = user_id
  and (
    workout_plan_id is null
    or exists (
      select 1
      from public.workout_plans
      where workout_plans.id = workout_plan_id
        and workout_plans.user_id = (select auth.uid())
    )
  )
);

drop policy if exists workout_exercise_logs_owner_all
  on public.workout_exercise_logs;
create policy workout_exercise_logs_owner_all
on public.workout_exercise_logs
for all
to authenticated
using ((select auth.uid()) = user_id)
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.workout_sessions
    where workout_sessions.id = workout_session_id
      and workout_sessions.user_id = (select auth.uid())
  )
);

drop policy if exists weight_logs_owner_all
  on public.weight_logs;
create policy weight_logs_owner_all
on public.weight_logs
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

revoke all on public.fitness_profiles from anon;
revoke all on public.workout_plans from anon;
revoke all on public.workout_sessions from anon;
revoke all on public.workout_exercise_logs from anon;
revoke all on public.weight_logs from anon;

grant select on public.exercises to anon, authenticated;
grant select, insert, update, delete
  on public.fitness_profiles,
     public.workout_plans,
     public.workout_sessions,
     public.workout_exercise_logs,
     public.weight_logs
  to authenticated;

grant usage, select on all sequences in schema public
  to authenticated;

commit;
